name: Deploy to Azure

on:
  push:
    paths:
      - "05-deployments/**"
    branches: [main]
  workflow_dispatch:

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies and test
        working-directory: ./05-deployments
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pytest -v

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        working-directory: ./05-deployments
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/fastapi-azure-app:latest .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/fastapi-azure-app:latest

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure Web App for Containers
        uses: azure/webapps-container-deploy@v1
        with:
          app-name: ${{ secrets.AZURE_WEBAPP_NAME }}
          images: ${{ secrets.DOCKERHUB_USERNAME }}/fastapi-azure-app:latest
